version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  backend:
    build: ./backend
    container_name: monkeypop-backend
    ports:
      - "3001:3001"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  frontend:
    build: ./frontend
    container_name: monkeypop-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis

  # Proxy to access K8s Services from localhost
  k8s-proxy:
    image: alpine/socat
    container_name: k8s-port-proxy
    restart: always
    entrypoint: ["sh", "-c"]
    ports:
      - "30001:30001" # Frontend
      - "30002:30002" # Backend
      - "30000:30000" # Grafana
      - "30090:30090" # Prometheus
    command: [
      "socat TCP-LISTEN:30001,fork,reuseaddr TCP:172.18.0.4:30001 & socat TCP-LISTEN:30002,fork,reuseaddr TCP:172.18.0.4:30002 & socat TCP-LISTEN:30000,fork,reuseaddr TCP:172.18.0.4:30000 & socat TCP-LISTEN:30090,fork,reuseaddr TCP:172.18.0.4:30090"
    ]
    networks:
      - default
      - kind

networks:
  default:
  kind:
    external: true

volumes:
  grafana-storage:
  jenkins-data:
  prometheus-data:
  redis-data:
