version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: monkeypop-backend
    ports:
      - "3001:3001"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  frontend:
    build: ./frontend
    container_name: monkeypop-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis

volumes:
  grafana-storage:
  jenkins-data:
