apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: monkeypop
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 30002
