- name: Deploy Frontend on Kubernetes
  hosts: server
  vars:
    version: "latest"
  tasks:
    - name: Apply frontend manifests
      shell: export KUBECONFIG=/var/jenkins_home/.kube/config; kubectl apply -f {{ playbook_dir }}/../../k8s/frontend-deployment.yaml -f {{ playbook_dir }}/../../k8s/frontend-service.yaml --validate=false

    - name: Set frontend image version
      shell: export KUBECONFIG=/var/jenkins_home/.kube/config; kubectl set image deployment/frontend frontend=thamonwanfirst/monkeypop-frontend:{{ version }} -n monkeypop

    - name: Force Rollout Restart
      shell: export KUBECONFIG=/var/jenkins_home/.kube/config; kubectl rollout restart deployment/frontend -n monkeypop
