
- name: Deploy Backend on Kubernetes
  hosts: server
  vars:
    version: "latest"   
  tasks:
    - name: Apply backend manifests
      shell: export KUBECONFIG=/var/jenkins_home/.kube/config; kubectl apply -f {{ playbook_dir }}/../../k8s/backend-deployment.yaml -f {{ playbook_dir }}/../../k8s/backend-service.yaml --validate=false

    - name: Set backend image version
      shell: export KUBECONFIG=/var/jenkins_home/.kube/config; kubectl set image deployment/backend backend=thamonwanfirst/monkeypop-backend:{{ version }} -n monkeypop

    - name: Force Rollout Restart
      shell: export KUBECONFIG=/var/jenkins_home/.kube/config; kubectl rollout restart deployment/backend -n monkeypop
