server ansible_host=172.17.176.23   ansible_connection=ssh  ansible_user=theeraphat_mag ansible_port=22
#server ansible_host=172.17.176.23 ansible_port=22 ansible_user=theeraphat_mag ansible_connection=ssh ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
